spring:
  datasource:
    uri: ${cloud.services.postgresql-db.uri}

  liquibase:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true