spring:
  datasource:
    url: ${vcap.services.postgreSQL-DB.credentials.url}
    username: ${vcap.services.postgreSQL-DB.credentials.username}
    password: ${vcap.services.postgreSQL-DB.credentials.password}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true