spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/pets
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    change-log: classpath:liquibase/master.xml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: info
    org.hibernate.type.descriptor.sql.BasicBinder: debug
    org.hibernate.SQL: debug