spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/pets
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:liquibase/master.xml
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/pets
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true