spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/pets
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver


  liquibase:
    change-log: classpath:liquibase/master.xml
    url: jdbc:postgresql://localhost:5433/pets
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true